---
- name: Exam preparation
  hosts: webserver1
  gather_facts: yes
  tasks:
    - block:
      - name: display OS version
        debug:
          msg: "{{ ansible_facts['distribution'] }}"
      - name: install httpd & mariadb
        yum:
          name:
            - httpd
            - mod_ssl
            - httpd-tools
            - php
            - php-mysqlnd
          state: latest
      - name: verify services are installed
        service:
          name: "{{ item }}"
          state: started
        loop:
          - httpd
      tags:
        - configure
    - name: write report
      copy:
        content: "{{ ansible_facts['fqdn'] is configured }}"
        dest: /root/report
      tags:
        - report
        - always
